<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('teachers')->insert([
            ['id' => 1, 'cv_url' => 'https://cv/hmc20qpial', 'level' => 'A1', 'address' => 'Ba Dinh', 'age' => 25, 'salary' => 100000, 'other_requirements' => '完全に学校に行く', 'phone' => '0982640564', 'avatar' => 'https://leminhhoang.vn/wp-content/uploads/2023/05/chon-loc-anh-avatar-buon.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Nguyen Thi Thu'],
            ['id' => 2, 'cv_url' => 'https://cv/yzaae6yuib', 'level' => 'A2', 'address' => 'Hoan Kiem', 'age' => 24, 'salary' => 80000, 'other_requirements' => '完全に学校に行く', 'phone' => '0347376412', 'avatar' => 'https://antimatter.vn/wp-content/uploads/2022/04/avatar-doi-nguoi-that-ngau-cho-nam.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Tran Van Minh'],
            ['id' => 3, 'cv_url' => 'https://cv/bl6xuxl036', 'level' => 'B1', 'address' => 'Hai Ba Trung', 'age' => 25, 'salary' => 150000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0912306573', 'avatar' => 'https://toigingiuvedep.vn/wp-content/uploads/2022/11/avatar-dep-nu-cho-con-gai.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Le Thi Anh'],
            ['id' => 4, 'cv_url' => 'https://cv/oy8e4uec17', 'level' => 'B2', 'address' => 'Dong Da', 'age' => 30, 'salary' => 120000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0363683946', 'avatar' => 'https://upanh123.com/wp-content/uploads/2020/12/avatar-nam.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Pham Duc Trung'],
            ['id' => 5, 'cv_url' => 'https://cv/dj5zprpi0e', 'level' => 'C1', 'address' => 'Tay Ho', 'age' => 26, 'salary' => 150000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0969888346', 'avatar' => 'https://anhdephd.vn/wp-content/uploads/2022/02/tai-anh-avatar-dep-hinh-dai-dien-facebook.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Vu Thi Mai Phuong'],
            ['id' => 6, 'cv_url' => 'https://cv/mp11vzhdjf', 'level' => 'C2', 'address' => 'Cau Giay', 'age' => 29, 'salary' => 100000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0982516983', 'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZiOs1UwbiYbjcA6S7fTzCYL4E-WrAwiYLG3eCDssLJKTtJLteogeRwAbcmqY0bjGnWGQ&usqp=CAU', 'sex' => 'male', 'status' => 'active', 'name' => 'Hoang Trung Hieu'],
            ['id' => 7, 'cv_url' => 'https://cv/xf8ltn3h0q', 'level' => 'A1', 'address' => 'Thanh Xuan', 'age' => 23, 'salary' => 100000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0989116325', 'avatar' => 'https://www.vivosmartphone.vn/uploads/MANGOADS/Selfie%20n%E1%BB%AF/A%20%C4%91%E1%BA%BFn%20Z/3.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Ngo Viet Bac'],
            ['id' => 8, 'cv_url' => 'https://cv/m1ikjue1oz', 'level' => 'A2', 'address' => 'Hoang Mai', 'age' => 28, 'salary' => 120000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0912906368', 'avatar' => 'https://toanthaydinh.com/wp-content/uploads/2020/04/avatar-dep-trai-10.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Nguyen Duc Long'],
            ['id' => 9, 'cv_url' => 'https://cv/0txm8txr0q', 'level' => 'B1', 'address' => 'Long Bien', 'age' => 32, 'salary' => 150000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0949336508', 'avatar' => 'https://leminhhoang.vn/wp-content/uploads/2023/05/chon-loc-anh-avatar-buon.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Bui Xuan Thuy'],
            ['id' => 10, 'cv_url' => 'https://cv/94t7zzef6j', 'level' => 'B2', 'address' => 'Bac Tu Liem', 'age' => 24, 'salary' => 100000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0363598471', 'avatar' => 'https://anhdep123.com/wp-content/uploads/2021/02/anh-hoc-sinh-dep.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Tran Huy Phuc'],
            ['id' => 11, 'cv_url' => 'https//cv/XEXnxOpCWy', 'level' => 'A1', 'address' => 'Nam Tu Liem', 'age' => 25, 'salary' => 150000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0912055371', 'avatar' => 'https://anhdep123.com/wp-content/uploads/2021/02/hinh-anh-trai-dep-dau-nam-2k4.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Nguyen Minh Khai'],
            ['id' => 12, 'cv_url' => 'https://cv/e5d48KM6l5', 'level' => 'A2', 'address' => 'Ha Dong', 'age' => 30, 'salary' => 100000, 'other_requirements' => '完全に学校に行く', 'phone' => '0906318966', 'avatar' => 'https://upanh123.com/wp-content/uploads/2020/12/hinh-anh-cute-nam1.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Tran Van Dang'],
            ['id' => 13, 'cv_url' => 'https://cv/mKcmSfevEi', 'level' => 'B1', 'address' => 'Son Tay', 'age' => 28, 'salary' => 150000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0363455987', 'avatar' => 'https://anhdephd.vn/wp-content/uploads/2022/02/tai-anh-avatar-dep-hinh-dai-dien-facebook.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Le Thi Hong Nhung'],
            ['id' => 14, 'cv_url' => 'https://cv/3BttkBfwR2', 'level' => 'B2', 'address' => 'Ba Vi', 'age' => 26, 'salary' => 100000, 'other_requirements' => '完全に学校に行く', 'phone' => '0982177035', 'avatar' => 'https://hanoispiritofplace.com/wp-content/uploads/2016/06/trai-dep-chau-au-4.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Pham Van Tuan'],
            ['id' => 15, 'cv_url' => 'https://cv/A3HK3slrA9', 'level' => 'C1', 'address' => 'Phuc Tho', 'age' => 27, 'salary' => 120000, 'other_requirements' => '完全に学校に行く', 'phone' => '0363559686', 'avatar' => 'https://toigingiuvedep.vn/wp-content/uploads/2022/11/avatar-dep-nu-cho-con-gai.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Do Thi Hai Yen'],
            ['id' => 16, 'cv_url' => 'https://cv/qI3KNd2BNJ', 'level' => 'C2', 'address' => 'Dan Phuong', 'age' => 29, 'salary' => 120000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0912067888', 'avatar' => 'https://toigingiuvedep.vn/wp-content/uploads/2022/11/avatar-dep-nu-cho-con-gai.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Vu Thi Thu Ha'],
            ['id' => 17, 'cv_url' => 'https://cv/oxTo8qMjq1', 'level' => 'A1', 'address' => 'Hoai Duc', 'age' => 23, 'salary' => 100000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0906318364', 'avatar' => 'https://toanthaydinh.com/wp-content/uploads/2020/04/avatar-dep-trai-10.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Hoang Van Tung'],
            ['id' => 18, 'cv_url' => 'https://cv/Z5qnmMflhs', 'level' => 'A2', 'address' => 'Thach That', 'age' => 25, 'salary' => 100000, 'other_requirements' => '完全に学校に行く', 'phone' => '0906358156', 'avatar' => 'https://antimatter.vn/wp-content/uploads/2022/04/avatar-doi-nguoi-that-ngau-cho-nam.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Ngo Thanh Tung'],
            ['id' => 19, 'cv_url' => 'https://cv/AXGPZQ4heG', 'level' => 'B1', 'address' => 'Quoc Oai', 'age' => 26, 'salary' => 120000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0363662179', 'avatar' => 'https://anhdephd.vn/wp-content/uploads/2022/02/tai-anh-avatar-dep-hinh-dai-dien-facebook.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Bui Thi Thu Huong'],
            ['id' => 20, 'cv_url' => 'https://cv/eI3kb8kYXY', 'level' => 'B2', 'address' => 'Chuong My', 'age' => 29, 'salary' => 100000, 'other_requirements' => '完全に学校に行く', 'phone' => '0982311569', 'avatar' => 'https://i.bloganchoi.com/bloganchoi.com/wp-content/uploads/2022/09/avatar-buon-2022-108.jpg?fit\u003d636%2C20000\u0026quality\u003d95\u0026ssl\u003d1', 'sex' => 'female', 'status' => 'active', 'name' => 'Ly Thi Mai Anh'],
            ['id' => 21, 'cv_url' => 'https://cv/kh7CDrPGqb', 'level' => 'C1', 'address' => 'Thanh Oai', 'age' => 24, 'salary' => 150000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0363549117', 'avatar' => 'https://toanthaydinh.com/wp-content/uploads/2020/04/avatar-dep-trai-10.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Tran Thanh Tam'],
            ['id' => 22, 'cv_url' => 'https://cv/mmtp2eH9PI', 'level' => 'C2', 'address' => 'Thuong Tin', 'age' => 25, 'salary' => 100000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0906382563', 'avatar' => 'https://thegioimay.org/wp-content/uploads/2020/11/57358127_1290006087821185_714335095200153600_n.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Nguyen Van Hieu'],
            ['id' => 23, 'cv_url' => 'https://cv/KDrSDmjp2m', 'level' => 'A1', 'address' => 'Phu Xuyen', 'age' => 26, 'salary' => 100000, 'other_requirements' => '完全に学校に行く', 'phone' => '0363982661', 'avatar' => 'https://leminhhoang.vn/wp-content/uploads/2023/05/chon-loc-anh-avatar-buon.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Phan Thi Thu Hien'],
            ['id' => 24, 'cv_url' => 'https://cv/LwYyznzu6u', 'level' => 'A2', 'address' => 'Me Linh', 'age' => 23, 'salary' => 120000, 'other_requirements' => '完全に学校に行く', 'phone' => '0982301446', 'avatar' => 'https://thegioimay.org/wp-content/uploads/2020/11/57358127_1290006087821185_714335095200153600_n.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Dang Van Hung'],
            ['id' => 25, 'cv_url' => 'https://cv/p2i3Zl95oU', 'level' => 'B1', 'address' => 'Dong Anh', 'age' => 28, 'salary' => 80000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0982306118', 'avatar' => 'https://leminhhoang.vn/wp-content/uploads/2023/05/chon-loc-anh-avatar-buon.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Le Thi Kim Ngan'],
            ['id' => 26, 'cv_url' => 'https://cv/bXVJBmCt4O', 'level' => 'B2', 'address' => 'Gia Lam', 'age' => 27, 'salary' => 120000, 'other_requirements' => '完全に学校に行く', 'phone' => '0906102456', 'avatar' => 'https://anhdep123.com/wp-content/uploads/2021/02/hinh-anh-trai-dep-dau-nam.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Tran Van Nam'],
            ['id' => 27, 'cv_url' => 'https://cv/Ak60s1qhrW', 'level' => 'A1', 'address' => 'Soc Son', 'age' => 32, 'salary' => 100000, 'other_requirements' => '完全に学校に行く', 'phone' => '0906782301', 'avatar' => 'https://anhdep123.com/wp-content/uploads/2021/02/hinh-anh-trai-dep-dau-nam-2k4.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Nguyen Thi Thu Ha'],
            ['id' => 28, 'cv_url' => 'https://cv/9DRBCtkXGa', 'level' => 'A2', 'address' => 'Thanh Tri', 'age' => 30, 'salary' => 100000, 'other_requirements' => '完全に学校に行く', 'phone' => '0306559101', 'avatar' => 'https://upanh123.com/wp-content/uploads/2020/12/hinh-anh-cute-nam1.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Pham Van Dung'],
            ['id' => 29, 'cv_url' => 'https://cv/v0lw6pJHUM', 'level' => 'B1', 'address' => 'My Duc', 'age' => 29, 'salary' => 120000, 'other_requirements' => '完全に学校に行く', 'phone' => '0363998203', 'avatar' => 'https://anhdep123.com/wp-content/uploads/2021/02/hinh-anh-trai-dep-dau-nam.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Dang Thanh Hai'],
            ['id' => 30, 'cv_url' => 'https://cv/kHvBuktpy4', 'level' => 'B2', 'address' => 'Ung Hoa', 'age' => 31, 'salary' => 150000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0936453117', 'avatar' => 'https://antimatter.vn/wp-content/uploads/2022/04/avatar-doi-nguoi-that-ngau-cho-nam.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Hoang Van Khanh'],
            ['id' => 31, 'cv_url' => 'https://cv/Skg8Boo5hL', 'level' => 'C1', 'address' => 'Ba Dinh', 'age' => 26, 'salary' => 150000, 'other_requirements' => '完全に学校に行く', 'phone' => '0969334781', 'avatar' => 'https://anhdep123.com/wp-content/uploads/2021/02/anh-hoc-sinh-dep.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Bui Duc Anh'],
            ['id' => 32, 'cv_url' => 'https://cv/8QWq8ZjmNk', 'level' => 'C2', 'address' => 'Hoan Kiem', 'age' => 24, 'salary' => 80000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0982635468', 'avatar' => 'https://i.bloganchoi.com/bloganchoi.com/wp-content/uploads/2022/09/avatar-buon-2022-108.jpg?fit\u003d636%2C20000\u0026quality\u003d95\u0026ssl\u003d1', 'sex' => 'female', 'status' => 'active', 'name' => 'Le Thi Thuy Linh'],
            ['id' => 33, 'cv_url' => 'https://cv/IzbCU18D1N', 'level' => 'A1', 'address' => 'Hai Ba Trung', 'age' => 28, 'salary' => 100000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0982107446', 'avatar' => 'https://i.bloganchoi.com/bloganchoi.com/wp-content/uploads/2022/09/avatar-buon-2022-108.jpg?fit\u003d636%2C20000\u0026quality\u003d95\u0026ssl\u003d1', 'sex' => 'female', 'status' => 'active', 'name' => 'Le Thi Kim Anh'],
            ['id' => 34, 'cv_url' => 'https://cv/EfCwjXLpGW', 'level' => 'A2', 'address' => 'Dong Da', 'age' => 26, 'salary' => 80000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0363198504', 'avatar' => 'https://hanoispiritofplace.com/wp-content/uploads/2016/06/trai-dep-chau-au-4.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Dinh Van Tu'],
            ['id' => 35, 'cv_url' => 'https://cv/Bw5DqVt68e', 'level' => 'B1', 'address' => 'Tay Ho', 'age' => 27, 'salary' => 120000, 'other_requirements' => '完全に学校に行く', 'phone' => '0912036558', 'avatar' => 'https://anhdep123.com/wp-content/uploads/2021/02/hinh-anh-trai-dep-dau-nam.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Pham Minh Tuan'],
            ['id' => 36, 'cv_url' => 'https://cv/rqdX0rlL8j', 'level' => 'B2', 'address' => 'Cau Giay', 'age' => 23, 'salary' => 80000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0906325110', 'avatar' => 'https://leminhhoang.vn/wp-content/uploads/2023/05/chon-loc-anh-avatar-buon.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Le Thi Anh Ngoc'],
            ['id' => 37, 'cv_url' => 'https://cv/Wz1ik06fuK', 'level' => 'C1', 'address' => 'Thanh Xuan', 'age' => 28, 'salary' => 100000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0912868360', 'avatar' => 'https://danviet.mediacdn.vn/upload/3-2017/images/2017-09-29/150668688163087-untitled-10.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Ngo Minh Hieu'],
            ['id' => 38, 'cv_url' => 'https://cv/Nhb2rEoObi', 'level' => 'C2', 'address' => 'Hoang Mai', 'age' => 25, 'salary' => 100000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0906537226', 'avatar' => 'https://antimatter.vn/wp-content/uploads/2022/04/avatar-doi-nguoi-that-ngau-cho-nam.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Tran Van Duc'],
            ['id' => 39, 'cv_url' => 'https://cv/DEkAD2z5Jf', 'level' => 'A1', 'address' => 'Long Bien', 'age' => 26, 'salary' => 120000, 'other_requirements' => '完全に学校に行く', 'phone' => '0363108337', 'avatar' => 'https://anhdephd.vn/wp-content/uploads/2022/03/anh-dai-dien-nu-deo-kinh-chat-600x600.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Vu Mai Anh'],
            ['id' => 41, 'cv_url' => 'https://cv/jjfRGmxiEO', 'level' => 'B1', 'address' => 'Nam Tu Liem', 'age' => 25, 'salary' => 80000, 'other_requirements' => '完全に学校に行く', 'phone' => '0989116302', 'avatar' => 'https://anhdephd.vn/wp-content/uploads/2022/03/anh-dai-dien-nu-deo-kinh-chat-600x600.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Le Thi Hong Nga'],
            ['id' => 42, 'cv_url' => 'https://cv/UBTcJwQeYW', 'level' => 'B2', 'address' => 'Ha Dong', 'age' => 30, 'salary' => 100000, 'other_requirements' => '完全に学校に行く', 'phone' => '0363549802', 'avatar' => 'https://antimatter.vn/wp-content/uploads/2022/04/avatar-doi-nguoi-that-ngau-cho-nam.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Ly Quoc Dung'],
            ['id' => 43, 'cv_url' => 'https://cv/pwKTHCat9O', 'level' => 'C1', 'address' => 'Son Tay', 'age' => 29, 'salary' => 100000, 'other_requirements' => '完全に学校に行く', 'phone' => '0912006875', 'avatar' => 'https://nhadepso.com/wp-content/uploads/2023/02/hinh-anh-trai-dep-han-quoc_1.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Nguyen Van Hung'],
            ['id' => 44, 'cv_url' => 'https://cv/GV8zDKeOC7', 'level' => 'C2', 'address' => 'Ba Vi', 'age' => 31, 'salary' => 100000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0969350248', 'avatar' => 'https://i.pinimg.com/236x/07/c0/82/07c08255c5973803c8b19d6a9ca01ab0.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Le Minh Tuan'],
            ['id' => 45, 'cv_url' => 'https://cv/EJITBMI5i7', 'level' => 'A1', 'address' => 'Phuc Tho', 'age' => 28, 'salary' => 150000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0363991845', 'avatar' => 'https://anhdep123.com/wp-content/uploads/2021/02/hinh-anh-trai-dep-dau-nam-2k4.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Bui Quang Minh'],
            ['id' => 46, 'cv_url' => 'https://cv/8T9TsCzwqU', 'level' => 'A2', 'address' => 'Dan Phuong', 'age' => 26, 'salary' => 120000, 'other_requirements' => '男子生徒のみ受け入れ可能', 'phone' => '0912006873', 'avatar' => 'https://i.pinimg.com/236x/07/c0/82/07c08255c5973803c8b19d6a9ca01ab0.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Do Van Tu'],
            ['id' => 47, 'cv_url' => 'https://cv/NR2dEvFdjG', 'level' => 'B1', 'address' => 'Hoai Duc', 'age' => 27, 'salary' => 100000, 'other_requirements' => '完全に学校に行く', 'phone' => '0969823065', 'avatar' => 'https://i.pinimg.com/236x/07/c0/82/07c08255c5973803c8b19d6a9ca01ab0.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Nguyen Van Hoan'],
            ['id' => 48, 'cv_url' => 'https://cv/aqVNtx56RS', 'level' => 'B2', 'address' => 'Thach That', 'age' => 33, 'salary' => 120000, 'other_requirements' => '完全に学校に行く', 'phone' => '0363118267', 'avatar' => 'https://scr.vn/wp-content/uploads/2020/07/Avt-%C4%91%E1%BA%B9p-cho-n%E1%BB%AF-1.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Nguyen Kim Lien'],
            ['id' => 49, 'cv_url' => 'https://cv/pI2f7nvJV7', 'level' => 'C1', 'address' => 'Quoc Oai', 'age' => 25, 'salary' => 150000, 'other_requirements' => '完全に学校に行く', 'phone' => '0982016774', 'avatar' => 'https://scr.vn/wp-content/uploads/2020/07/Avt-%C4%91%E1%BA%B9p-cho-n%E1%BB%AF-1.jpg', 'sex' => 'female', 'status' => 'active', 'name' => 'Dang Thu Thao'],
            ['id' => 50, 'cv_url' => 'https://cv/HAhEB9QVwE', 'level' => 'C2', 'address' => 'Chuong My', 'age' => 26, 'salary' => 100000, 'other_requirements' => '女子学生のみ受け入れ可能', 'phone' => '0912085696', 'avatar' => 'https://antimatter.vn/wp-content/uploads/2022/04/avatar-doi-nguoi-that-ngau-cho-nam.jpg', 'sex' => 'male', 'status' => 'active', 'name' => 'Tran Minh Sang']
        ]);
    }
}
